version: '3.2'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./config:/docker-entrypoint-initdb.d
    networks:
      main:
        ipv4_address: 172.12.1.3
    environment:
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    build: ./
    image: hybris
    volumes:
      - ./wp-core:/var/www/html
    networks:
      main:
        ipv4_address: 172.12.1.2
    ports:
      - "3000:80"

networks:
  main:
    driver: bridge
    ipam:
     config:
        - subnet: 172.12.1.0/24