version: '3.2'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./config:/docker-entrypoint-initdb.d
    networks:
      main:
        ipv4_address: 172.12.1.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress

  wordpress:
    build: ./
    image: hybris
    volumes:
      - ./themes:/var/www/html/wp-content/themes
    networks:
      main:
        ipv4_address: 172.12.1.2
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

networks:
  main:
    driver: bridge
    ipam:
     config:
        - subnet: 172.12.1.0/24